type Post {
  id: ID!
  title: String!
  description: String
  category: String
  location: String
  photoUrl: String
  type: String # "lost" or "found"
  reward: Float
  contactVisible: Boolean
  createdAt: Timestamp
  userId: String
}

type Query {
  getPosts: [Post] @firestoreRead(collection: "posts")
  getPostById(id: ID!): Post @firestoreRead(collection: "posts", id: "id")
}

type Mutation {
  addPost(
    title: String!
    description: String
    category: String
    location: String
    photoUrl: String
    type: String
    reward: Float
    contactVisible: Boolean
    userId: String
  ): Post @firestoreCreate(collection: "posts")

  deletePost(id: ID!): Boolean @firestoreDelete(collection: "posts", id: "id")
}
